[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "poc-server-ntt-ai"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastmcp==3.0.0b2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]